# Generated by Django 4.0.4 on 2022-06-06 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('address', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('course', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150)),
                ('course_type', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('percentage', models.IntegerField()),
                ('year_of_passing', models.IntegerField()),
                ('skills', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('experience_level', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('responsibilities', models.TextField()),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('worked_from', models.DateTimeField()),
                ('to', models.DateTimeField()),
                ('about_company', models.TextField()),
                ('website', models.URLField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
