# Generated by Django 4.0.4 on 2022-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetail_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
