# Generated by Django 4.0.4 on 2022-06-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userdetail_about_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='experience_level',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
