# Generated by Django 4.0.4 on 2022-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userdetail_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
