# Generated by Django 4.0.4 on 2022-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userdetail_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
