# Generated by Django 4.0.4 on 2022-06-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userdetail_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
