# Generated by Django 4.0.4 on 2022-06-06 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('about_company', models.TextField()),
                ('website', models.URLField()),
                ('openings', models.IntegerField()),
                ('no_of_applicants', models.IntegerField()),
                ('application_deadline', models.DateTimeField()),
                ('recruter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
