# Generated by Django 4.0.4 on 2022-06-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_applicantdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='skills',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
