# Generated by Django 4.0.4 on 2022-06-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_jobdetail_about_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='recruter_id',
            new_name='recruiter_id',
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
