# Generated by Django 4.0.4 on 2022-06-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_recruter_id_jobdetail_recruiter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='application_deadline',
            field=models.DateField(),
        ),
    ]
