# Generated by Django 4.0.4 on 2022-06-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobdetail_application_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='skills',
            new_name='Skills',
        ),
    ]
