# Generated by Django 4.0.4 on 2022-06-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_skills_jobdetail_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='Skills',
        ),
    ]
